- web_frontend/src/components/SeniorMain.tsx
- web_frontend/src/core/router.tsx
> [design] SeniorMain UI 스타일링

- web_frontend/src/components/seniorSchedule/TodoItem.tsx
- web_frontend/src/components/seniorSchedule/TodoList.tsx
- web_frontend/src/components/seniorSchedule/TodoMain.tsx
- web_frontend/src/components/seniorSchedule/seniorSchedule.tsx
- web_frontend/src/core/router.tsx
> [design] seniorSchedule UI를 위한 스타일링

- backend/server/src/main/java/capstone/server/user_guardian/entity/UserGuardian.java
- backend/server/src/main/java/capstone/server/utils/BaseTimeEntity.java
> [feat] userGuardian Entity 구현

- backend/server/src/main/java/capstone/server/user_ward/entity/UserWard.java
- backend/server/src/main/java/capstone/server/utils/BaseTimeEntity.java
- close #11 
- 스키마에 적용한 컬럼 및 테이블명이 일치하는지 재차 확인 필요 ( 코드 컨벤션 )
> [feat] userWard 엔티티 구현

- backend/server/src/main/java/capstone/server/entity/UserGuardian.java
- backend/server/src/main/java/capstone/server/entity/UserWard.java
- close #18 
- 도메인이 미확정이여서, 기존 사용하던 패키지 구조에서 수정이 필요하다고 판단했습니다.
> [fix] 엔티티 패키지 구조 수정

- backend/server/src/main/java/capstone/server/entity/Medicine.java
- backend/server/src/main/java/capstone/server/entity/UserGuardian.java
- backend/server/src/main/java/capstone/server/entity/UserWard.java
> [Backend/feat] medicine Entity 구현

- backend/server/src/main/java/capstone/server/entity/MedicalHistoryCategory.java
- backend/server/src/main/java/capstone/server/entity/MedicalHistoryUserWardHas.java
> [Backend/feat] medicalHistoryCategory Entity 구현, userWard와 매핑

- backend/server/src/main/java/capstone/server/entity/UserGuardianUserWard.java
- backend/server/src/main/java/capstone/server/entity/UserGuardianUserWardEach.java
> [Backend/feat] userGuardianuserWardEach 엔티티 구현

- backend/server/src/main/java/capstone/server/global/dto/ErrorResponse.java
- close #43 
{
status : HttpStatus
result : boolean
message : String
}
- /
> [feat] ErrorResponse 공통 사용 Dto 구현

- backend/server/src/main/java/capstone/server/config/WebConfig.java
> [Backend/fix] CORS 재설정

- backend/server/src/main/java/capstone/server/domain/food/controller/FoodController.java
- backend/server/src/main/java/capstone/server/domain/food/service/FoodService.java
- backend/server/src/main/java/capstone/server/domain/food/service/FoodServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/medicine/service/MedicineServiceImpl.java
> [Backend/chore] foodRecognition -> foodDetection명칭 변경, API주소 프로퍼티에 추가하여 보안강화

- backend/server/src/main/java/capstone/server/domain/medicine/controller/MedicineController.java
- backend/server/src/main/java/capstone/server/domain/medicine/service/MedicineService.java
- backend/server/src/main/java/capstone/server/domain/medicine/service/MedicineServiceImpl.java
- close #59
- DELETE /medicine/{id}
> [Backend/deleteMedicine] 약 삭제 기능 구현

- backend/server/src/main/java/capstone/server/config/SwaggerConfig.java
> [chore] Swagger에서 JWT 사용 가능하도록 수정

- backend/server/src/main/java/capstone/server/domain/login/exception/ExceptionManager.java
- backend/server/src/main/java/capstone/server/domain/workout/controller/WorkOutController.java
- backend/server/src/main/java/capstone/server/domain/workout/dto/GetAllWorkOutCategoryResponse.java
- backend/server/src/main/java/capstone/server/domain/workout/dto/RegisterWorkOutRequest.java
- backend/server/src/main/java/capstone/server/domain/workout/dto/WorkOutCategoryDtoResponse.java
- backend/server/src/main/java/capstone/server/domain/workout/dto/WorkOutCategoryResponse.java
- backend/server/src/main/java/capstone/server/domain/workout/dto/WorkOutRecordResponse.java
- backend/server/src/main/java/capstone/server/domain/workout/enums/WorkOutCategoryEnum.java
- backend/server/src/main/java/capstone/server/domain/workout/repository/WorkOutCategoryRepository.java
- backend/server/src/main/java/capstone/server/domain/workout/repository/WorkOutCategoryUserWardHasRepository.java
- backend/server/src/main/java/capstone/server/domain/workout/service/WorkOutService.java
- backend/server/src/main/java/capstone/server/domain/workout/service/WorkOutServiceImpl.java
- backend/server/src/main/java/capstone/server/entity/WorkOutCategory.java
- backend/server/src/main/java/capstone/server/entity/WorkOutUserWardHas.java
- backend/server/src/main/java/capstone/server/global/WorkOutCategoryCommandLineRunner.java
- backend/server/src/main/java/capstone/server/global/dto/DefaultResponse.java
- close #66 
- /api/workout/categories
- /api/workout
- /api/workout/records
> [Backend/workout] 운동 서비스 로직 구현

- backend/server/src/main/java/capstone/server/domain/food/controller/FoodController.java
- backend/server/src/main/java/capstone/server/domain/food/dto/FoodInfo.java
- backend/server/src/main/java/capstone/server/domain/food/dto/GetFoodInfoResponseDto.java
- backend/server/src/main/java/capstone/server/domain/food/dto/MealInfo.java
- backend/server/src/main/java/capstone/server/domain/food/dto/RegisterFoodDto.java
- backend/server/src/main/java/capstone/server/domain/food/repository/FoodRepository.java
- backend/server/src/main/java/capstone/server/domain/food/repository/MealRepository.java
- backend/server/src/main/java/capstone/server/domain/food/service/FoodService.java
- backend/server/src/main/java/capstone/server/domain/food/service/FoodServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/medicine/controller/MedicineController.java
- backend/server/src/main/java/capstone/server/entity/Food.java
- backend/server/src/main/java/capstone/server/entity/Meal.java
- close #62
- /api/food
- /api/food/detect
> [Backend/Food] 음식 등록 기능, GET 기능 구현

- backend/server/src/main/java/capstone/server/domain/workout/enums/WorkOutCategoryEnum.java
- close #75 
- 이름이 너무 길어서 수정
- /
> [Backend/workout] 레크레이션 이름 수정

- backend/server/src/main/java/capstone/server/domain/workout/controller/WorkOutController.java
- backend/server/src/main/java/capstone/server/domain/workout/service/WorkOutService.java
- backend/server/src/main/java/capstone/server/domain/workout/service/WorkOutServiceImpl.java
- close #71 
- /api/workout/records/{id}
> [Backend/workout] 운동력 삭제 기능 구현

- backend/server/src/main/java/capstone/server/domain/workout/dto/WorkOutRecordResponse.java
- backend/server/src/main/java/capstone/server/entity/WorkOutUserWardHas.java
> [Backend/workout] 운동력 반환시 hour 정보 추가

- backend/server/src/main/java/capstone/server/domain/medicine/controller/MedicineController.java
- backend/server/src/main/java/capstone/server/domain/medicine/dto/ModifyMedicineDto.java
- backend/server/src/main/java/capstone/server/domain/medicine/service/MedicineService.java
- backend/server/src/main/java/capstone/server/domain/medicine/service/MedicineServiceImpl.java
- backend/server/src/main/java/capstone/server/utils/BaseTimeEntity.java
- close #83
- [patch] /api/medicine/{id}
> [Backend/Medicine] 약 정보 수정기능 구현

- backend/server/src/main/java/capstone/server/domain/medicine/controller/MedicineController.java
- backend/server/src/main/java/capstone/server/domain/medicine/service/MedicineServiceImpl.java
> [Backend/fix] 오타수정 및 남은 복용일수 안넘어가던 버그 수정

- backend/server/src/main/java/capstone/server/domain/food/controller/FoodController.java
- backend/server/src/main/java/capstone/server/domain/food/repository/MealRepository.java
- backend/server/src/main/java/capstone/server/domain/food/service/FoodService.java
- backend/server/src/main/java/capstone/server/domain/food/service/FoodServiceImpl.java
- close #87
- /api/food/date="yyyy-mm"
> [Backend/Food] 먹은 음식 보내줄때, 월별로 조회가능 하게 수정, 에러리스폰스 리팩토링

- backend/server/src/main/java/capstone/server/domain/food/repository/MealRepository.java
- backend/server/src/main/java/capstone/server/domain/user/controller/UserWardController.java
- backend/server/src/main/java/capstone/server/domain/user/dto/GetUserWardMainInfoResponseDto.java
- backend/server/src/main/java/capstone/server/domain/user/dto/getUserWardMainInfoResponseDto.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardService.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/workout/repository/WorkOutCategoryUserWardHasRepository.java
- close #88 
- /api/userward/main
> [Backend/SeniorMain] 노인 메인페이지에 필요한 API작성

- backend/server/src/main/java/capstone/server/entity/Medicine.java
> [Backend/Medicine] 약정보 스트링 글자수 3000자로 확장

- backend/server/src/main/java/capstone/server/domain/calendar/controller/CalendarController.java
- backend/server/src/main/java/capstone/server/domain/calendar/dto/GetRecordsDateResponseDto.java
- backend/server/src/main/java/capstone/server/domain/calendar/service/CalendarService.java
- backend/server/src/main/java/capstone/server/domain/calendar/service/CalendarServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/food/repository/MealRepository.java
- backend/server/src/main/java/capstone/server/domain/workout/repository/WorkOutCategoryUserWardHasRepository.java
> [Backend/Calendar] 캘린더에 사용할 데이터들의 날짜 API작성

- web_frontend/package.json
- web_frontend/src/components/common/SeniorCalendar.tsx
- web_frontend/src/core/api/index.ts
- web_frontend/src/core/router.tsx
- web_frontend/src/pages/SeniorExericseMainPage.tsx
- web_frontend/yarn.lock
> [Frontend/Calendar] 데이터를 보여주는 캘린더 뷰, 기능 구현

- backend/server/src/main/java/capstone/server/domain/user/dto/GetUserWardMainInfoResponseDto.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardServiceImpl.java
> [Backend/SeniorMain] 메인화면에 유저이름 넘겨주도록 수정

- backend/server/src/main/java/capstone/server/domain/food/repository/MealRepository.java
- backend/server/src/main/java/capstone/server/domain/user/controller/UserWardController.java
- backend/server/src/main/java/capstone/server/domain/user/dto/DailySummaryDto.java
- backend/server/src/main/java/capstone/server/domain/user/dto/ExerciseInfo.java
- backend/server/src/main/java/capstone/server/domain/user/dto/FoodInfo.java
- backend/server/src/main/java/capstone/server/domain/user/dto/GetDailySummaryDto.java
- backend/server/src/main/java/capstone/server/domain/user/dto/MealInfo.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardService.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardServiceImpl.java
- close #115
- /api/userward/summary/daily
> [Backend/DailySummary] 일일요약에 사용할 데이터리스트 API작성

- backend/server/src/main/java/capstone/server/ServerApplication.java
> [Backend] 실행시에 TimeZone 서울시간으로 하도록 설정

- backend/server/src/main/java/capstone/server/domain/food/repository/MealRepository.java
- backend/server/src/main/java/capstone/server/domain/login/service/JoinServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/medical/dto/MedicalHistoryInfo.java
- backend/server/src/main/java/capstone/server/domain/medical/repository/MedicalHistoryCategoryRepository.java
- backend/server/src/main/java/capstone/server/domain/medical/repository/MedicalHistoryUserWardHasRepository.java
- backend/server/src/main/java/capstone/server/domain/user/controller/UserWardController.java
- backend/server/src/main/java/capstone/server/domain/user/dto/GetWeeklySummaryDto.java
- backend/server/src/main/java/capstone/server/domain/user/dto/WeeklyExerciseRecord.java
- backend/server/src/main/java/capstone/server/domain/user/dto/WeeklyFoodNutrient.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardService.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/workout/repository/WorkOutCategoryUserWardHasRepository.java
- backend/server/src/main/java/capstone/server/entity/MedicalHistoryCategory.java
- backend/server/src/main/java/capstone/server/global/MedicalCategoryCommandLineRunner.java
- backend/server/src/main/java/capstone/server/global/WorkOutCategoryCommandLineRunner.java
- close #issue_number
제공데이터
- 이름
- 성별
- 나이
- 키, 몸무게
- 음주, 흠연 빈도
- 보유질병
- 일주간 영양소
- 일주간 운동 정보
```JSON
{
"name": "홍길동",
"gender": "MALE",
"age": 7,
"weight": 0,
"height": 0,
"drinkings": 0,
"smoke": 1,
"medicalHistory": [
{
"kor": "고혈압",
"eng": "highBloodPressure",
"description": null
},
{
"kor": "당뇨",
"eng": "diabetes",
"description": null
}
],
"weeklyFoodNutrientSum": [
{
"date": "2023-04-27",
"calorie": 1,
"carbohydrate": 2,
"protein": 2,
"fat": 2,
"cholesterol": 2,
"natrium": 2
},
{
"date": "2023-04-28",
"calorie": 1,
"carbohydrate": 2,
"protein": 2,
"fat": 2,
"cholesterol": 2,
"natrium": 2
},
{
"date": "2023-04-29",
"calorie": 1,
"carbohydrate": 2,
"protein": 2,
"fat": 2,
"cholesterol": 2,
"natrium": 2
},
{
"date": "2023-04-30",
"calorie": 0,
"carbohydrate": 0,
"protein": 0,
"fat": 0, …
```
> [Backend/SeniorSummary] 주간 데이터 요약에 필요한 데이터리스트 API작성

- .github/workflows/gradle.yml
- close #127 
- workflows작성
- /
> [DevOps] github Action workflows작성

- .github/workflows/gradle.yml
- close #127 
- 상대 경로 설정으로 gradlew 경로 안잡히는 문제 해결을 위해서
- /
> [Devops] gradlew 상대경로 절대경로로 수정

- .github/workflows/gradle.yml
Reverts kookmin-sw/capstone-2023-11#131
> Revert "[Devops] gradlew 상대경로 절대경로로 수정"

- .github/workflows/gradle.yml
> [fix] gradlew경로에러로 다시 잡아줌

- .github/workflows/gradle.yml
Reverts kookmin-sw/capstone-2023-11#135
> Revert "Back/#127"

- .github/workflows/gradle.yml
- backend/server/appspec.yml
- backend/server/build.gradle
- backend/server/scripts/start.sh
- backend/server/scripts/stop.sh
> [Devops] 배포자동화 구축

- .github/workflows/gradle.yml
> [fix] push할때만 적용되도록 수정

- web_frontend/src/components/seniorSummary/FoodDetailPopUp.tsx
- web_frontend/src/core/atom.tsx
- web_frontend/src/pages/SeniorSummaryDailyPage.tsx
> [Frontend/SeniorSummaryDay] 시니어 일간 데이터 부가 기능 구현

- web_frontend/src/components/seniorPill/PillAddModal.tsx
- web_frontend/src/core/router.tsx
- web_frontend/src/pages/GuardianJoinPage.tsx
- web_frontend/src/pages/KakaoAuthPage.tsx
- web_frontend/src/pages/SeniorExerciseAddPage.tsx
- web_frontend/src/pages/SeniorExericseMainPage.tsx
- web_frontend/src/pages/SeniorJoinPage.tsx
- web_frontend/src/pages/SeniorMealCheckPage.tsx
- web_frontend/src/pages/SeniorPillMainPage.tsx
- web_frontend/src/pages/SeniorPillSelfAddPage.tsx
- web_frontend/src/pages/SeniorSummaryDailyPage.tsx
> [Frontend/BugFix] 버그 및 디자인 수정

- backend/server/src/main/java/capstone/server/domain/login/dto/GuardianJoinRequest.java
- backend/server/src/main/java/capstone/server/domain/login/dto/WardJoinRequest.java
- backend/server/src/main/java/capstone/server/domain/login/service/JoinServiceImpl.java
- backend/server/src/main/java/capstone/server/entity/UserGuardian.java
- backend/server/src/main/java/capstone/server/entity/UserWard.java
> [Backeend/signup] 회원가입시 이메일 등록하도록 수정

- web_frontend/src/core/atom.tsx
- web_frontend/src/core/router.tsx
- web_frontend/src/pages/GuardianJoinPage.tsx
- web_frontend/src/pages/KakaoAuthPage.tsx
- web_frontend/src/pages/SeniorJoinPage.tsx
> [Frontend/Join] 회원가입시 이름 추가

- backend/server/src/main/java/capstone/server/domain/login/dto/GuardianJoinRequest.java
- backend/server/src/main/java/capstone/server/domain/login/dto/WardJoinRequest.java
- backend/server/src/main/java/capstone/server/domain/login/service/JoinServiceImpl.java
- backend/server/src/main/java/capstone/server/entity/UserGuardian.java
- backend/server/src/main/java/capstone/server/entity/UserWard.java
Reverts kookmin-sw/capstone-2023-11#156
> Revert "[Backeend/signup] 회원가입시 이메일 등록하도록 수정"

- backend/server/src/main/java/capstone/server/domain/notification/service/NotificationServiceImpl.java
- backend/server/src/main/resources/templates/food-mail.html
> [Backend/Notification] 날짜 파싱, 끼니, 링크 연결

- backend/server/src/main/java/capstone/server/domain/medical/repository/MedicalHistoryUserWardHasRepository.java
- backend/server/src/main/java/capstone/server/domain/user/controller/UserWardController.java
- backend/server/src/main/java/capstone/server/domain/user/dto/GetUserWardMainInfoResponseDto.java
- backend/server/src/main/java/capstone/server/domain/user/dto/UserWardInfoDto.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardService.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardServiceImpl.java
- close #167 
- /api/userward/modify
> [Backend/SeniorMypage] 시니어 마이페이지 개인정보 수정 api

- web_frontend/src/components/seniorPill/SeniorMainPill.tsx
- web_frontend/src/components/seniorSummary/Advice.tsx
- web_frontend/src/core/atom.tsx
- web_frontend/src/pages/SeniorPillBillAddPage.tsx
- web_frontend/src/pages/SeniorPillDetailPage.tsx
- web_frontend/src/pages/SeniorPillSelfAddPage.tsx
- web_frontend/src/pages/SeniorSummaryPage.tsx
> [Frondend/SeniorPill] 약 관련 컴포넌트 에러 및 로직 수정

- web_frontend/src/pages/SeniorMainPage.tsx
> [Frontend/SeniorMain] 노인 메인 페이지 디자인 수정

- web_frontend/src/core/api/index.ts
- web_frontend/src/core/atom.tsx
- web_frontend/src/core/router.tsx
- web_frontend/src/pages/GuardianJoinPage.tsx
- web_frontend/src/pages/SeniorExerciseAddPage.tsx
- web_frontend/src/pages/SeniorExericseMainPage.tsx
- web_frontend/src/pages/SeniorJoinPage.tsx
- web_frontend/src/pages/SeniorMainPage.tsx
- web_frontend/src/pages/SeniorModifyPage.tsx
- web_frontend/src/pages/SeniorMypage.tsx
> [Frontend/SeniorMyPage] 시니어 마이페이지 개인정보 수정 뷰 디자인 및 구현

- web_frontend/src/components/common/BackButton.tsx
- web_frontend/src/components/common/BlueButton.tsx
- web_frontend/src/components/common/BottomNav.tsx
- web_frontend/src/components/common/KakaoLoginButton.tsx
- web_frontend/src/components/seniorExercise/ExerciseList.tsx
- web_frontend/src/components/seniorExercise/ExercisePopUp.tsx
- web_frontend/src/components/seniorPill/PillAddModal.tsx
- web_frontend/src/components/seniorPill/SeniorMainNoPill.tsx
- web_frontend/src/components/seniorPill/SeniorMainPill.tsx
- web_frontend/src/pages/GuardianJoinPage.tsx
- web_frontend/src/pages/LoginPage.tsx
- web_frontend/src/pages/SeniorExerciseAddPage.tsx
- web_frontend/src/pages/SeniorExericseMainPage.tsx
- web_frontend/src/pages/SeniorJoinPage.tsx
- web_frontend/src/pages/SeniorMainPage.tsx
- web_frontend/src/pages/SeniorMealCheckPage.tsx
- web_frontend/src/pages/SeniorMealMain.tsx
- web_frontend/src/pages/SeniorModifyPage.tsx
- web_frontend/src/pages/SeniorMypage.tsx
- web_frontend/src/pages/SeniorPillBillAddPage.tsx
- web_frontend/src/pages/SeniorPillDetailPage.tsx
- web_frontend/src/pages/SeniorPillMainPage.tsx
- web_frontend/src/pages/SeniorPillSelfAddPage.tsx
- web_frontend/src/pages/SeniorSummaryDailyPage.tsx
- web_frontend/src/pages/SeniorSummaryPage.tsx
> [Frontend/Animation&Summary] 일간, 주간 헤더 드롭다운 추가 및 컴포넌트 애니메이션 추가

- web_frontend/src/pages/SeniorSummaryDailyPage.tsx
- web_frontend/src/pages/SeniorSummaryPage.tsx
> [Frontend/SeniorSummary] 주간, 일간 보고서 문구 및 버그 수정

- backend/server/src/main/java/capstone/server/domain/user/controller/UserGuardianController.java
- backend/server/src/main/java/capstone/server/domain/user/controller/UserWardController.java
- backend/server/src/main/java/capstone/server/domain/user/dto/ConnectedGuardian.java
- backend/server/src/main/java/capstone/server/domain/user/repository/UserWardRepository.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserGuardianService.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserGuardianServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardService.java
- backend/server/src/main/java/capstone/server/domain/user/service/UserWardServiceImpl.java
- close #188 
- /userward/connected-guardians
> [Backend/SeniorMypage] 시니어 마이페이지 연결 보호자 확인 api + 보호자 뷰에서 복약정보 조회기능 추가

- web_frontend/src/pages/SeniorMealMain.tsx
- web_frontend/src/pages/SeniorSummaryPage.tsx
- 시니어 주간 보고서 게이지 바 추가
- 음식 메인 디테일 팝업 추가
> [Frontend/SeniorSummary] 시니어 주간 보고서 게이지 바 추가 , 음식 메인 디테일 팝업 추가

- backend/server/src/main/java/capstone/server/domain/calendar/controller/CalendarController.java
- backend/server/src/main/java/capstone/server/domain/calendar/service/CalendarServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/food/controller/FoodController.java
- backend/server/src/main/java/capstone/server/domain/food/service/FoodServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/medicine/controller/MedicineController.java
- backend/server/src/main/java/capstone/server/domain/medicine/service/MedicineService.java
- backend/server/src/main/java/capstone/server/domain/medicine/service/MedicineServiceImpl.java
- backend/server/src/main/java/capstone/server/domain/user/controller/UserWardController.java
> [Backend] 지금까지짠 코드 리팩토링

- backend/server/src/main/java/capstone/server/domain/medicine/service/MedicineServiceImpl.java
> [Backend] MedicineService API상수 final 지정관련 버그수정

- web_frontend/src/components/seniorExercise/ExercisePopUp.tsx
- web_frontend/src/core/api/index.ts
- web_frontend/src/core/atom.tsx
- web_frontend/src/pages/SeniorCheckGuardian.tsx
- web_frontend/src/pages/SeniorMypage.tsx
> [Frontend/SeniorMyPage] 시니어 마이페이지 등록되어있는 보호자 확인 기능 추가

- backend/server/src/main/java/capstone/server/domain/notification/service/NotificationServiceImpl.java
> [fix] 이메일 값 null 또는 blank일시 안보내도록 처리

- backend/server/src/main/java/capstone/server/domain/user/controller/UserGuardianController.java
> [Backend] @RequestParam을 @PathVariable로 등록해서 오류발생한 버그수정

- web_frontend/src/pages/SeniorPillBillAddPage.tsx
> [Frontend/SeniorPill] 복약봉투 인식 관련 버그 수정

- web_frontend/package.json
- web_frontend/src/components/guardianPill/GuardianMainNoPill.tsx
- web_frontend/src/components/guardianPill/GuardianMainPill.tsx
- web_frontend/src/components/seniorSummary/CalChart.tsx
- web_frontend/src/components/seniorSummary/CalComment.tsx
- web_frontend/src/components/seniorSummary/ExerciseChart.tsx
- web_frontend/src/components/seniorSummary/ExerciseComment.tsx
- web_frontend/src/core/router.tsx
- web_frontend/src/pages/GuardianExerciseMainViewPage.tsx
- web_frontend/src/pages/GuardianMainPage.tsx
- web_frontend/src/pages/GuardianMainViewPage.tsx
- web_frontend/src/pages/GuardianMealMainViewPage.tsx
- web_frontend/src/pages/GuardianPillDetalViewPage.tsx
- web_frontend/src/pages/GuardianPillMainViewPage.tsx
- web_frontend/src/pages/GuardianSummaryDailyPage.tsx
- web_frontend/src/pages/GuardianSummaryPage.tsx
- web_frontend/src/pages/SeniorCheckGuardian.tsx
- web_frontend/src/pages/SeniorPillSelfAddPage.tsx
- web_frontend/yarn.lock
- yarn.lock
> [Frontend/GuardianMain] 보호자 메인 화면 뷰 및 기능 구현

- web_frontend/src/components/seniorSummary/Advice.tsx
> [Frontend/Advice] 보고서 GPT api를 이용한 총평 수정

- web_frontend/src/components/common/Loading.tsx
- web_frontend/src/components/seniorSummary/Advice.tsx
- web_frontend/src/components/seniorSummary/CalChart.tsx
- web_frontend/src/core/api/index.ts
- web_frontend/src/pages/GuardianMainPage.tsx
- web_frontend/src/pages/SeniorJoinPage.tsx
- web_frontend/src/pages/SeniorMealCheckPage.tsx
- web_frontend/src/pages/SeniorPillSelfAddPage.tsx
> [Frontend/GuardianMain] 보호자 메인 화면 시니어 추가 및 삭제 기능 구현

- web_frontend/src/pages/SeniorMainPage.tsx
> [Frontend/GuardianMain] 보호자 메인 화면 문구 수정
